# -*- coding: utf-8 -*-
"""Wav2Lip_quick_trial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tZpDWXz49W6wDcTprANRGLo2D_EbD5J8

# Collab preliminaries
"""

!nvcc --version

from google.colab import drive
drive.mount('/content/gdrive')

"""# Get the code and models"""

!git clone https://github.com/Rudrabha/Wav2Lip.git

!ls /content/gdrive/MyDrive/Wav2Lip

!cp -ri "/content/gdrive/MyDrive/Wav2Lip/wav2lip_gan.pth" /content/Wav2Lip/checkpoints/

"""# Get the pre-requisites"""

!pip uninstall tensorflow tensorflow-gpu

!cd Wav2Lip && pip install -r requirements.txt

!wget "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" -O "Wav2Lip/face_detection/detection/sfd/s3fd.pth"

"""# Now lets try!"""

!cp "/content/gdrive/My Drive/Wav2Lip/test.mp4" "/content/gdrive/My Drive/Wav2Lip/test.wav" sample_data/
!ls sample_data/

!cd Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "../sample_data/test.mp4" --audio "../sample_data/test.wav"

# use the "files" button on the left to download the result in the Wav2Lip/results/ folder.

"""## **Variations to try**

1.   Use more padding to include the chin region
"""

!cd Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "../sample_data/test.mp4" --audio "../sample_data/sdfnsdkgnjksdgv.wav" --pads 0 20 0 0

"""2.   Use resize_factor to reduce the video resolution, as there is a change you might get better results for lower resolution videos. Why? Because the model was trained on low resolution faces."""

!cd Wav2Lip && python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth --face "../sample_data/input_vid.mp4" --audio "../sample_data/input_audio.wav" --resize_factor 2